### ISSUE TITLE
command 'rmarkdown_vscode.rmarkdown-core.Knit' not found

### ISSUE THREAD

**Issue by MaveriQ** [TianyiShi2001/rmarkdown-vscode#1] opened 2020-04-17 07:13 UTC
Hi

I installed the extension but when I try to Knit an Rmd file by `Ctrl+Shift+K`, I get the error `command 'rmarkdown_vscode.rmarkdown-core.Knit' not found`. I have installed R and it's working fine. I can also access R in vscode. 

Thank you

**Comment by TianyiShi2001** [comment] 2020-04-17 16:27
Sorry about this. 

It worked well on my Mac, but when I tried using Linux, I experienced the same issue. I'm now trying to figure out how to fix this.

**Comment by TianyiShi2001** [comment] 2020-04-19 05:09
Hopefully It has been fixed.

**Comment by TianyiShi2001** [comment] 2020-04-19 05:27
Hopefully it has been fixed in v0.0.14. I've tested on Mac and Linux. 
You may need to [manually set](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file) the language of the file to be rmarkdown.

<img width="585" alt="图片" src="https://user-images.githubusercontent.com/38644266/79680356-5f34c380-8241-11ea-8189-fc09c8052e9b.png">

**Closed** 2020-04-19 05:27 UTC
Labels: bug, help wanted

**Comment by TianyiShi2001** [comment] 2020-04-19 05:31
I don't know why, but using webpack seemed to fix it.

**Comment by gusbemacbe** [comment] 2021-06-30 03:41
Hello @TianyiShi2001 !

I am on Linux. I file-associated R Markdown files and pressed the command `Knit to All Formats`. It worked. The problem is that, when you output to all the formats, the files were outside the right folder where a R Markdown file is in. 

Blogdown failed because it picked the wrong workspace project. The `config.toml` and `default.rmd` are in another folder. The error log:

```
Error in site_root(config, .site_dir) : 
  Could not find config.toml / config.yaml under
   /home/gusbemacbe/Cursos/Udemy/100 Days of Code – Python
   /home/gusbemacbe/Cursos/Udemy
   /home/gusbemacbe/Cursos
   /home/gusbemacbe
   /home
   /
Calls: <Anonymous> -> serve -> site_root
Execution halted

```

See the tree, where it picked the folder `100 Days of Code – Python` instead of the folder `Unidade 02 – Estruturas de Controle e Funções em R`. 

![imagem](https://user-images.githubusercontent.com/2257024/123898030-e51ac700-d93a-11eb-9b6c-7716057e272a.png)

To continue the Blogdown test. I moved these files to the folder `100 Days of Code – Python` and served the site... It worked perfectly. As I have already knoweldge of Hugo, it will be easy for me. What works with Hugo on Linux, also works with Blogdown. 

![imagem](https://user-images.githubusercontent.com/2257024/123898358-94579e00-d93b-11eb-8267-14fcecbb2e1f.png)

You have to advise the Linux users to install all the TexLive packages for Linux and the TinyTex for R. For Blogdown, they should be advised to run `install.packages("blogdown")` before serve the site. 

As knitting to all the formats and serving the site with Blogdown worked well on Linux, you can remove `It has been reported to fail on Linux` from README. But you need to fix the wrong commands where Blogdown picked the wrong folders up as you were seeing the workspace.
